### ISSUE TITLE
"InvalidUserCodeException: Task.project Invocation Unsupported in buildIl2Cpp Task

### ISSUE THREAD

**Issue by zeoowl-dev** [teogor/drifter#5]
When attempting to execute the `:module-unity:buildIl2Cpp` task in our Gradle build, we encounter an `InvalidUserCodeException` with the following error message:
```
Caused by: org.gradle.api.InvalidUserCodeException: Invocation of 'Task.project' by task ':module-unity:buildIl2Cpp' at execution time is unsupported.
```

**Steps to Reproduce:**
1. Run the Gradle build process that includes the `:module-unity:buildIl2Cpp` task.

**Expected Behavior:**
The `:module-unity:buildIl2Cpp` task should execute without errors.

**Actual Behavior:**
The task encounters an `InvalidUserCodeException` with the mentioned error message.

**Additional Information:**
- This issue seems to be related to accessing the `project` property within the `@TaskAction` method of the `buildIl2Cpp` task.
- We need assistance in refactoring the task to resolve this issue and ensure that it correctly configures and executes without invoking `Task.project` during execution.

**Comment by teogor** [comment]
We appreciate your detailed description and steps to reproduce the problem. Rest assured, we are actively working on resolving this issue promptly.

The error you're encountering, `InvalidUserCodeException`, is indeed related to accessing the `project` property within the `@TaskAction` method of the `buildIl2Cpp` task, which is currently unsupported and can lead to issues during task execution.

To address this, we'll need to refactor the `buildIl2Cpp` task to avoid accessing the `project` property during execution. Our goal is to make the necessary adjustments to the plugin code to ensure the task runs smoothly without invoking `Task.project`.

We will keep you updated on our progress and provide a new plugin version once this issue is resolved. In the meantime, if you have any additional information or insights that could help us, please feel free to share them.

Thank you for your patience and understanding. We are committed to resolving this issue as soon as possible. You can expect the fix in `drifter-plugin` version `1.0.0-alpha02`.

**Comment by teogor** [comment]
Great news! 🎉 The issue regarding the implementation of Ceres Plugins has been successfully resolved with the implementation of the plugins in the latest pull request titled #6 

All the required Ceres Plugins have been added, and they are now configured to reference the ceres-plugin version. This ensures that the project is up-to-date and ready to utilize these plugins as needed. 🚀

**Comment by zeoowl-dev** [comment]
Thank you! We'll check it out once the next library version is released.
